export { default as Badgeclass } from "./Badgeclass.svelte";
export { default as BadgeclassEdit } from "./BadgeclassEdit.svelte";
export { default as Badgeclasses } from "./Badgeclasses.svelte";
export { default as BadgeclassForm } from "./BadgeclassForm.svelte";
export { default as BadgeclassNew } from "./BadgeclassNew.svelte";
export { default as BadgesAwarded } from "./BadgesAwarded.svelte";
export { default as BadgesRequested } from "./BadgesRequested.svelte";
export { default as BadgesRevoked } from "./BadgesRevoked.svelte";
export { default as Breadcrumb } from "./Breadcrumb.svelte";
export { default as EntityForm } from "./EntityForm.svelte";
export { default as EntityHeader } from "./EntityHeader.svelte";
export { default as EntityHeaderTabs } from "./EntityHeaderTabs.svelte";
export { default as Faculties } from "./Faculties.svelte";
export { default as Faculty } from "./Faculty.svelte";
export { default as FacultyEdit } from "./FacultyEdit.svelte";
export { default as FacultyForm } from "./FacultyForm.svelte";
export { default as FacultyNew } from "./FacultyNew.svelte";
export { default as FilterBlock } from "./FilterBlock.svelte";
export { default as Header } from "./Header.svelte";
export { default as Institution } from "./Institution.svelte";
export { default as InstitutionEdit } from "./InstitutionEdit.svelte";
export { default as Issuer } from "./Issuer.svelte";
export { default as IssuerEdit } from "./IssuerEdit.svelte";
export { default as IssuerForm } from "./IssuerForm.svelte";
export { default as IssuerNew } from "./IssuerNew.svelte";
export { default as Issuers } from "./Issuers.svelte";
export { default as SideBar } from "./SideBar.svelte";
export { default as Table } from "./Table.svelte";
export { default as AwardBadge } from "./AwardBadge.svelte"
export { default as AwardBadgeForm } from "./AwardBadgeForm.svelte"
export { default as AwardManyBadges } from "./AwardManyBadges.svelte"
