export const data = {
    "assertions": [ {
            "award_type": "direct_award",
            "badgeclass_id": 3,
            "badgeclass__name": "Cognitive Psychology",
            "badgeclass__archived": false,
            "badgeclass__badge_class_type": "regular",
            "issuer_id": 18,
            "public": true,
            "revoked": false,
            "issuer__name_dutch": null,
            "issuer__name_english": "Psychology",
            "issuer__faculty_id": 7,
            "issuer__faculty__name_dutch": null,
            "issuer__faculty__name_english": "Social and Behavioural Science",
            "issuer__faculty__faculty_type": null,
            "issuer__faculty__institution__institution_type": "HBO",
            "year": 2023,
            "month": 6,
            "nbr": 3
        }],
    "direct_awards": [{
            "status": "Unaccepted",
            "badgeclass_id": 24,
            "badgeclass__name": "History of Political Thought",
            "badgeclass__archived": false,
            "badgeclass__issuer__id": 40,
            "badgeclass__badge_class_type": "regular",
            "badgeclass__issuer__name_dutch": null,
            "badgeclass__issuer__name_english": "Political Science",
            "badgeclass__issuer__faculty_id": 13,
            "badgeclass__issuer__faculty__name_dutch": "Dutch name issuer group",
            "badgeclass__issuer__faculty__name_english": "Virtual Organisation Social and Behavioural Science",
            "badgeclass__issuer__faculty__faculty_type": "HBO",
            "badgeclass__issuer__faculty__institution__institution_type": "HBO/MBO",
            "year": 2023,
            "month": 6,
            "nbr": 4
        } ],
    "enrollments": [
        {
            "denied": true,
            "badge_class_id": 7,
            "badge_class__name": "insights-bug",
            "badge_class__issuer__id": 38,
            "badge_class__badge_class_type": "regular",
            "badge_class__issuer__name_dutch": null,
            "badge_class__issuer__name_english": "Psychology Change",
            "badge_class__issuer__faculty_id": 13,
            "badge_class__issuer__faculty__name_dutch": "Dutch name issuer group",
            "badge_class__issuer__faculty__name_english": "Virtual Organisation Social and Behavioural Science",
            "badge_class__issuer__faculty__faculty_type": "HBO",
            "badge_class__issuer__faculty__institution__institution_type": "HBO/MBO",
            "year": 2023,
            "month": 6,
            "nbr": 1
        }
    ],
    "direct_award_bundles": [],
    "users_count": 5,
    "faculties_count": 6,
    "issuers_count": 8,
    "badge_class_count": 7,
    "backpack_count": 6
}