name: Docker Image CI

permissions:
  id-token: write
  attestations: write

on:
  push:
    branches: ["feature/ewi"]
    tags:
      - ewi-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to SDP Container Registry "Harbor"
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: cr.surf.nl
          username: ${{ secrets.CR_SURF_USERNAME }}
          password: ${{ secrets.CR_SURF_PASSWORD }}

      - name: Get tag
        id: git_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "GIT_TAG=git-tag-${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "HAS_TAG=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_TAG=false" >> $GITHUB_OUTPUT
          fi

      # For every commit, we build a :latest
      # For git tags, e.g. 'ewi-1.2.3', we build both ':latest-test' and ':ewi-1.2.3'
      - name: Build and push Docker image
        id: push-image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
           cr.surf.nl/edubadges-edubadges/edubadges/edubadges-ui:latest
           ${{ steps.git_tag.outputs.HAS_TAG == 'true' && format('cr.surf.nl/edubadges-edubadges/edubadges/edubadges-ui:{0}', 'latest-test') || '' }}
           ${{ steps.git_tag.outputs.HAS_TAG == 'true' && format('cr.surf.nl/edubadges-edubadges/edubadges/edubadges-ui:{0}', steps.git_tag.outputs.GIT_TAG) || '' }}

      - name: Generate artifact attestation for latest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: cr.surf.nl/edubadges-edubadges/edubadges/edubadges-ui
          subject-digest: ${{ steps.push-image.outputs.digest }}
          push-to-registry: true
